# Strategy Constants
RSI_LEN = 14
RSI_THRESHOLD = 50

# Relative Strength (RS)
RS_SMA_LEN = 20
INDEX_SYMBOL = "^NSEI" # Nifty 50 for RS calculation

# Volume Footprint
VOL_SMA_LEN = 20
VOL_MULT = 1.2

# Telegram Settings
TELEGRAM_MAX_SIGNALS = 20
TELEGRAM_SEND_SIGNALS = True
TELEGRAM_SEND_WATCH = True
TELEGRAM_SEND_ELIGIBLE = True

# Risk Params
ACCOUNT_SIZE = 1000000
RISK_PER_TRADE = 0.02 # 2%
MAX_POS_PCT = 0.20 # 20%

TELEGRAM_BOT_TOKEN=123456:AAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
TELEGRAM_CHAT_ID=123456789
